version: "3.8"

services:
  yolo-api:
    build: 
      context: .
      dockerfile: Dockerfile  # Uses your existing Dockerfile
    ports:
      - "8000:8000"
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - yolo-api  # Ensure YOLO API starts before backend
    restart: always

  frontend:
    image: nginx:alpine  # Use official Nginx image
    ports:
      - "5173:80"  # Serve on port 5173
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro  # Mount built files
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use a custom Nginx config
    depends_on:
      - backend
    restart: always
